### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by 0verse** [glaz-lang/glaz#1]
Hello, I,ve this build issue when compiling from the source:

> Building compiler...
> src/ast/gmod.glaz:37:19: error: expected `main::ast::TypeInfo`, not `main::ast::TupleInfo`, in field `info`
>      | 
>   37 |             info: TupleInfo{
>      |

**Comment by 0verse** [comment]
Also building with "python testc.py examples/hello_world.glaz" throws this error:

> glazc error: error while compiling the output file `glaz.output.c`:
> /an/duyum/etki/ld: /tmp/cccCokMc.o: in function `print_backtrace':
> /ev/çizeylemcil/glaz/glaz.output.c:811: undefined reference to `backtrace'
> /an/duyum/etki/ld: /ev/çizeylemcil/glaz/glaz.output.c:820: undefined reference to `backtrace_symbols'
> collect2: error: ld returned 1 exit status

**Comment by StunxFS** [comment]
@0verse, it's weird, it works fine for me. What version of Pyhon do you use? I use 3.8 and 3.9﻿

**Comment by 0verse** [comment]
I use version 3.9.7

**Comment by StunxFS** [comment]
try this:

```
$ git clone https://github.com/glaz-lang/glaz
$ cd glaz
$ python3 build_compiler.py 
```

should work fine﻿

**Comment by 0verse** [comment]
I am afraid it gives the same error.

**Comment by 0verse** [comment]
I still get the same error with python3.8.

**Comment by 0verse** [comment]
I've tried compiling on my laptop that has linux mint x64 installed with defaults to python 3.8. I get this error:

> Building compiler...
> Traceback (most recent call last):
>   File "testc.py", line 7, in <module>
>     glazc.main.main(sys.argv[1:])
>   File "/home/sofia/glaz/glazc/main.py", line 51, in main
>     b.run()
>   File "/home/sofia/glaz/glazc/builder.py", line 40, in run
>     Generator(self.ctx).run()
>   File "/home/sofia/glaz/glazc/generator.py", line 74, in run
>     self.gen_files(self.ctx.files)
>   File "/home/sofia/glaz/glazc/generator.py", line 211, in gen_files
>     self.gen_file(file)
>   File "/home/sofia/glaz/glazc/generator.py", line 215, in gen_file
>     self.gen_declarations(file.nodes)
>   File "/home/sofia/glaz/glazc/generator.py", line 235, in gen_declarations
>     self.gen_function(decl)
>   File "/home/sofia/glaz/glazc/generator.py", line 319, in gen_function
>     self.gen_stmt(stmt)
>   File "/home/sofia/glaz/glazc/generator.py", line 350, in gen_stmt
>     self.gen_assign_stmt(stmt)
>   File "/home/sofia/glaz/glazc/generator.py", line 434, in gen_assign_stmt
>     self.gen_expr_with_cast(right, obj.typ)
>   File "/home/sofia/glaz/glazc/generator.py", line 1431, in gen_expr_with_cast
>     self.gen_expr(expr)
>   File "/home/sofia/glaz/glazc/generator.py", line 695, in gen_expr
>     self.gen_expr(expr.expr)
>   File "/home/sofia/glaz/glazc/generator.py", line 745, in gen_expr
>     self.gen_call_expr(expr)
>   File "/home/sofia/glaz/glazc/generator.py", line 928, in gen_call_expr
>     self.gen_expr_with_cast(arg.expr, carg.typ)
>   File "/home/sofia/glaz/glazc/generator.py", line 1431, in gen_expr_with_cast
>     self.gen_expr(expr)
>   File "/home/sofia/glaz/glazc/generator.py", line 739, in gen_expr
>     self.gen_unary_expr(expr)
>   File "/home/sofia/glaz/glazc/generator.py", line 785, in gen_unary_expr
>     if self.inside_return:
> AttributeError: 'Generator' object has no attribute 'inside_return'
> Compilation failed!

**Comment by StunxFS** [comment]
that error is already fixed:)﻿

**Comment by 0verse** [comment]
Yes I updated to the latest commits and I am able to compile successfully :) I guess I need to try on alpine linux, which is base on musl-libc and see if there is same error as well.

**Comment by 0verse** [comment]
I've tried compiling with alpine linux and I get the same error as well. I tried building glaz inside the chroot environment with python 3.9, resulting with equal error message:

> Building compiler...
> src/ast/gmod.glaz:37:19: error: expected `main::ast::TypeInfo`, not `main::ast::TupleInfo`, in field `info`
>      | 
>   37 |             info: TupleInfo{
>      |                   ^         
> Compilation failed!
